// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_pdu.proto

package fksproto;

public final class CsPdu {
  private CsPdu() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code fksproto.CSPDUEncryptMethod}
   *
   * <pre>
   * protocol format
   * dwLength(4bytes) + wVersion(2bytes) + wPBHeadLen(2bytes) + PB(CSPDUPBHead) + PB(Request)
   * </pre>
   */
  public enum CSPDUEncryptMethod
          implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ENCRYPT_METHOD_NONE = 0;</code>
     *
     * <pre>
     *不加密
     * </pre>
     */
    ENCRYPT_METHOD_NONE(0, 0),
    /**
     * <code>ENCRYPT_METHOD_AES = 1;</code>
     *
     * <pre>
     *AES对称加密
     * </pre>
     */
    ENCRYPT_METHOD_AES(1, 1),
    /**
     * <code>ENCRYPT_METHOD_RSA = 2;</code>
     *
     * <pre>
     *RSA非对称加密
     * </pre>
     */
    ENCRYPT_METHOD_RSA(2, 2),
    ;

    /**
     * <code>ENCRYPT_METHOD_NONE = 0;</code>
     *
     * <pre>
     *不加密
     * </pre>
     */
    public static final int ENCRYPT_METHOD_NONE_VALUE = 0;
    /**
     * <code>ENCRYPT_METHOD_AES = 1;</code>
     *
     * <pre>
     *AES对称加密
     * </pre>
     */
    public static final int ENCRYPT_METHOD_AES_VALUE = 1;
    /**
     * <code>ENCRYPT_METHOD_RSA = 2;</code>
     *
     * <pre>
     *RSA非对称加密
     * </pre>
     */
    public static final int ENCRYPT_METHOD_RSA_VALUE = 2;


    public final int getNumber() { return value; }

    public static CSPDUEncryptMethod valueOf(int value) {
      switch (value) {
        case 0: return ENCRYPT_METHOD_NONE;
        case 1: return ENCRYPT_METHOD_AES;
        case 2: return ENCRYPT_METHOD_RSA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CSPDUEncryptMethod>
    internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CSPDUEncryptMethod>
            internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CSPDUEncryptMethod>() {
              public CSPDUEncryptMethod findValueByNumber(int number) {
                return CSPDUEncryptMethod.valueOf(number);
              }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
      return fksproto.CsPdu.getDescriptor().getEnumTypes().get(0);
    }

    private static final CSPDUEncryptMethod[] VALUES = values();

    public static CSPDUEncryptMethod valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
                "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CSPDUEncryptMethod(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:fksproto.CSPDUEncryptMethod)
  }

  /**
   * Protobuf enum {@code fksproto.CSPDUCompressMethod}
   */
  public enum CSPDUCompressMethod
          implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>COMPRESS_METHOD_NONE = 0;</code>
     *
     * <pre>
     *不压缩
     * </pre>
     */
    COMPRESS_METHOD_NONE(0, 0),
    /**
     * <code>COMPRESS_METHOD_GZIP = 1;</code>
     *
     * <pre>
     *gzip压缩
     * </pre>
     */
    COMPRESS_METHOD_GZIP(1, 1),
    ;

    /**
     * <code>COMPRESS_METHOD_NONE = 0;</code>
     *
     * <pre>
     *不压缩
     * </pre>
     */
    public static final int COMPRESS_METHOD_NONE_VALUE = 0;
    /**
     * <code>COMPRESS_METHOD_GZIP = 1;</code>
     *
     * <pre>
     *gzip压缩
     * </pre>
     */
    public static final int COMPRESS_METHOD_GZIP_VALUE = 1;


    public final int getNumber() { return value; }

    public static CSPDUCompressMethod valueOf(int value) {
      switch (value) {
        case 0: return COMPRESS_METHOD_NONE;
        case 1: return COMPRESS_METHOD_GZIP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CSPDUCompressMethod>
    internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CSPDUCompressMethod>
            internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CSPDUCompressMethod>() {
              public CSPDUCompressMethod findValueByNumber(int number) {
                return CSPDUCompressMethod.valueOf(number);
              }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
      return fksproto.CsPdu.getDescriptor().getEnumTypes().get(1);
    }

    private static final CSPDUCompressMethod[] VALUES = values();

    public static CSPDUCompressMethod valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
                "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CSPDUCompressMethod(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:fksproto.CSPDUCompressMethod)
  }

  /**
   * Protobuf enum {@code fksproto.CSPDUAuthType}
   */
  public enum CSPDUAuthType
          implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AUTH_TYPE_NONE = 0;</code>
     */
    AUTH_TYPE_NONE(0, 0),
    /**
     * <code>AUTH_TYPE_SSO = 1;</code>
     *
     * <pre>
     *sso
     * </pre>
     */
    AUTH_TYPE_SSO(1, 1),
    /**
     * <code>AUTH_TYPE_WXAUTH = 2;</code>
     *
     * <pre>
     *wxauth       
     * </pre>
     */
    AUTH_TYPE_WXAUTH(2, 2),
    /**
     * <code>AUTH_TYPE_QQAUTH = 3;</code>
     *
     * <pre>
     *qqauth
     * </pre>
     */
    AUTH_TYPE_QQAUTH(3, 3),
    ;

    /**
     * <code>AUTH_TYPE_NONE = 0;</code>
     */
    public static final int AUTH_TYPE_NONE_VALUE = 0;
    /**
     * <code>AUTH_TYPE_SSO = 1;</code>
     *
     * <pre>
     *sso
     * </pre>
     */
    public static final int AUTH_TYPE_SSO_VALUE = 1;
    /**
     * <code>AUTH_TYPE_WXAUTH = 2;</code>
     *
     * <pre>
     *wxauth       
     * </pre>
     */
    public static final int AUTH_TYPE_WXAUTH_VALUE = 2;
    /**
     * <code>AUTH_TYPE_QQAUTH = 3;</code>
     *
     * <pre>
     *qqauth
     * </pre>
     */
    public static final int AUTH_TYPE_QQAUTH_VALUE = 3;


    public final int getNumber() { return value; }

    public static CSPDUAuthType valueOf(int value) {
      switch (value) {
        case 0: return AUTH_TYPE_NONE;
        case 1: return AUTH_TYPE_SSO;
        case 2: return AUTH_TYPE_WXAUTH;
        case 3: return AUTH_TYPE_QQAUTH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CSPDUAuthType>
    internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CSPDUAuthType>
            internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CSPDUAuthType>() {
              public CSPDUAuthType findValueByNumber(int number) {
                return CSPDUAuthType.valueOf(number);
              }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
      return fksproto.CsPdu.getDescriptor().getEnumTypes().get(2);
    }

    private static final CSPDUAuthType[] VALUES = values();

    public static CSPDUAuthType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
                "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CSPDUAuthType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:fksproto.CSPDUAuthType)
  }

  public interface CSPDUPBHeadBaseOrBuilder extends
          // @@protoc_insertion_point(interface_extends:fksproto.CSPDUPBHeadBase)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 msgid = 1;</code>
     */
    boolean hasMsgid();
    /**
     * <code>required int32 msgid = 1;</code>
     */
    int getMsgid();

    /**
     * <code>required int32 encrypt_method = 2;</code>
     *
     * <pre>
     *please look at enum CSPDUEncryptMethod
     * </pre>
     */
    boolean hasEncryptMethod();
    /**
     * <code>required int32 encrypt_method = 2;</code>
     *
     * <pre>
     *please look at enum CSPDUEncryptMethod
     * </pre>
     */
    int getEncryptMethod();

    /**
     * <code>required int32 compress_method = 3;</code>
     *
     * <pre>
     *please look at enum CSPDUCompressMethod
     * </pre>
     */
    boolean hasCompressMethod();
    /**
     * <code>required int32 compress_method = 3;</code>
     *
     * <pre>
     *please look at enum CSPDUCompressMethod
     * </pre>
     */
    int getCompressMethod();

    /**
     * <code>optional int32 result = 4;</code>
     */
    boolean hasResult();
    /**
     * <code>optional int32 result = 4;</code>
     */
    int getResult();
  }
  /**
   * Protobuf type {@code fksproto.CSPDUPBHeadBase}
   */
  public static final class CSPDUPBHeadBase extends
          com.google.protobuf.GeneratedMessage implements
          // @@protoc_insertion_point(message_implements:fksproto.CSPDUPBHeadBase)
          CSPDUPBHeadBaseOrBuilder {
    // Use CSPDUPBHeadBase.newBuilder() to construct.
    private CSPDUPBHeadBase(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSPDUPBHeadBase(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSPDUPBHeadBase defaultInstance;
    public static CSPDUPBHeadBase getDefaultInstance() {
      return defaultInstance;
    }

    public CSPDUPBHeadBase getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSPDUPBHeadBase(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              encryptMethod_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              compressMethod_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              result_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHeadBase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHeadBase_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      fksproto.CsPdu.CSPDUPBHeadBase.class, fksproto.CsPdu.CSPDUPBHeadBase.Builder.class);
    }

    public static com.google.protobuf.Parser<CSPDUPBHeadBase> PARSER =
            new com.google.protobuf.AbstractParser<CSPDUPBHeadBase>() {
              public CSPDUPBHeadBase parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new CSPDUPBHeadBase(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<CSPDUPBHeadBase> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MSGID_FIELD_NUMBER = 1;
    private int msgid_;
    /**
     * <code>required int32 msgid = 1;</code>
     */
    public boolean hasMsgid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 msgid = 1;</code>
     */
    public int getMsgid() {
      return msgid_;
    }

    public static final int ENCRYPT_METHOD_FIELD_NUMBER = 2;
    private int encryptMethod_;
    /**
     * <code>required int32 encrypt_method = 2;</code>
     *
     * <pre>
     *please look at enum CSPDUEncryptMethod
     * </pre>
     */
    public boolean hasEncryptMethod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 encrypt_method = 2;</code>
     *
     * <pre>
     *please look at enum CSPDUEncryptMethod
     * </pre>
     */
    public int getEncryptMethod() {
      return encryptMethod_;
    }

    public static final int COMPRESS_METHOD_FIELD_NUMBER = 3;
    private int compressMethod_;
    /**
     * <code>required int32 compress_method = 3;</code>
     *
     * <pre>
     *please look at enum CSPDUCompressMethod
     * </pre>
     */
    public boolean hasCompressMethod() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 compress_method = 3;</code>
     *
     * <pre>
     *please look at enum CSPDUCompressMethod
     * </pre>
     */
    public int getCompressMethod() {
      return compressMethod_;
    }

    public static final int RESULT_FIELD_NUMBER = 4;
    private int result_;
    /**
     * <code>optional int32 result = 4;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 result = 4;</code>
     */
    public int getResult() {
      return result_;
    }

    private void initFields() {
      msgid_ = 0;
      encryptMethod_ = 0;
      compressMethod_ = 0;
      result_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEncryptMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCompressMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, encryptMethod_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, compressMethod_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, msgid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(2, encryptMethod_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(3, compressMethod_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(4, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fksproto.CsPdu.CSPDUPBHeadBase parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fksproto.CsPdu.CSPDUPBHeadBase parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fksproto.CsPdu.CSPDUPBHeadBase parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fksproto.CsPdu.CSPDUPBHeadBase parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fksproto.CsPdu.CSPDUPBHeadBase parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fksproto.CsPdu.CSPDUPBHeadBase parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fksproto.CsPdu.CSPDUPBHeadBase parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fksproto.CsPdu.CSPDUPBHeadBase parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fksproto.CsPdu.CSPDUPBHeadBase parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fksproto.CsPdu.CSPDUPBHeadBase parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fksproto.CsPdu.CSPDUPBHeadBase prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fksproto.CSPDUPBHeadBase}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:fksproto.CSPDUPBHeadBase)
            fksproto.CsPdu.CSPDUPBHeadBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHeadBase_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHeadBase_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        fksproto.CsPdu.CSPDUPBHeadBase.class, fksproto.CsPdu.CSPDUPBHeadBase.Builder.class);
      }

      // Construct using fksproto.CsPdu.CSPDUPBHeadBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        encryptMethod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        compressMethod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHeadBase_descriptor;
      }

      public fksproto.CsPdu.CSPDUPBHeadBase getDefaultInstanceForType() {
        return fksproto.CsPdu.CSPDUPBHeadBase.getDefaultInstance();
      }

      public fksproto.CsPdu.CSPDUPBHeadBase build() {
        fksproto.CsPdu.CSPDUPBHeadBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fksproto.CsPdu.CSPDUPBHeadBase buildPartial() {
        fksproto.CsPdu.CSPDUPBHeadBase result = new fksproto.CsPdu.CSPDUPBHeadBase(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgid_ = msgid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.encryptMethod_ = encryptMethod_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.compressMethod_ = compressMethod_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fksproto.CsPdu.CSPDUPBHeadBase) {
          return mergeFrom((fksproto.CsPdu.CSPDUPBHeadBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fksproto.CsPdu.CSPDUPBHeadBase other) {
        if (other == fksproto.CsPdu.CSPDUPBHeadBase.getDefaultInstance()) return this;
        if (other.hasMsgid()) {
          setMsgid(other.getMsgid());
        }
        if (other.hasEncryptMethod()) {
          setEncryptMethod(other.getEncryptMethod());
        }
        if (other.hasCompressMethod()) {
          setCompressMethod(other.getCompressMethod());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgid()) {

          return false;
        }
        if (!hasEncryptMethod()) {

          return false;
        }
        if (!hasCompressMethod()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        fksproto.CsPdu.CSPDUPBHeadBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fksproto.CsPdu.CSPDUPBHeadBase) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgid_ ;
      /**
       * <code>required int32 msgid = 1;</code>
       */
      public boolean hasMsgid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 msgid = 1;</code>
       */
      public int getMsgid() {
        return msgid_;
      }
      /**
       * <code>required int32 msgid = 1;</code>
       */
      public Builder setMsgid(int value) {
        bitField0_ |= 0x00000001;
        msgid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgid = 1;</code>
       */
      public Builder clearMsgid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgid_ = 0;
        onChanged();
        return this;
      }

      private int encryptMethod_ ;
      /**
       * <code>required int32 encrypt_method = 2;</code>
       *
       * <pre>
       *please look at enum CSPDUEncryptMethod
       * </pre>
       */
      public boolean hasEncryptMethod() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 encrypt_method = 2;</code>
       *
       * <pre>
       *please look at enum CSPDUEncryptMethod
       * </pre>
       */
      public int getEncryptMethod() {
        return encryptMethod_;
      }
      /**
       * <code>required int32 encrypt_method = 2;</code>
       *
       * <pre>
       *please look at enum CSPDUEncryptMethod
       * </pre>
       */
      public Builder setEncryptMethod(int value) {
        bitField0_ |= 0x00000002;
        encryptMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 encrypt_method = 2;</code>
       *
       * <pre>
       *please look at enum CSPDUEncryptMethod
       * </pre>
       */
      public Builder clearEncryptMethod() {
        bitField0_ = (bitField0_ & ~0x00000002);
        encryptMethod_ = 0;
        onChanged();
        return this;
      }

      private int compressMethod_ ;
      /**
       * <code>required int32 compress_method = 3;</code>
       *
       * <pre>
       *please look at enum CSPDUCompressMethod
       * </pre>
       */
      public boolean hasCompressMethod() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 compress_method = 3;</code>
       *
       * <pre>
       *please look at enum CSPDUCompressMethod
       * </pre>
       */
      public int getCompressMethod() {
        return compressMethod_;
      }
      /**
       * <code>required int32 compress_method = 3;</code>
       *
       * <pre>
       *please look at enum CSPDUCompressMethod
       * </pre>
       */
      public Builder setCompressMethod(int value) {
        bitField0_ |= 0x00000004;
        compressMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 compress_method = 3;</code>
       *
       * <pre>
       *please look at enum CSPDUCompressMethod
       * </pre>
       */
      public Builder clearCompressMethod() {
        bitField0_ = (bitField0_ & ~0x00000004);
        compressMethod_ = 0;
        onChanged();
        return this;
      }

      private int result_ ;
      /**
       * <code>optional int32 result = 4;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 result = 4;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>optional int32 result = 4;</code>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000008;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 result = 4;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000008);
        result_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fksproto.CSPDUPBHeadBase)
    }

    static {
      defaultInstance = new CSPDUPBHeadBase(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:fksproto.CSPDUPBHeadBase)
  }

  public interface CSPDUPBHeadExtOrBuilder extends
          // @@protoc_insertion_point(interface_extends:fksproto.CSPDUPBHeadExt)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 uin = 1;</code>
     */
    boolean hasUin();
    /**
     * <code>required int32 uin = 1;</code>
     */
    int getUin();

    /**
     * <code>required string ticket = 2;</code>
     */
    boolean hasTicket();
    /**
     * <code>required string ticket = 2;</code>
     */
    java.lang.String getTicket();
    /**
     * <code>required string ticket = 2;</code>
     */
    com.google.protobuf.ByteString
    getTicketBytes();
  }
  /**
   * Protobuf type {@code fksproto.CSPDUPBHeadExt}
   */
  public static final class CSPDUPBHeadExt extends
          com.google.protobuf.GeneratedMessage implements
          // @@protoc_insertion_point(message_implements:fksproto.CSPDUPBHeadExt)
          CSPDUPBHeadExtOrBuilder {
    // Use CSPDUPBHeadExt.newBuilder() to construct.
    private CSPDUPBHeadExt(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSPDUPBHeadExt(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSPDUPBHeadExt defaultInstance;
    public static CSPDUPBHeadExt getDefaultInstance() {
      return defaultInstance;
    }

    public CSPDUPBHeadExt getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSPDUPBHeadExt(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uin_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              ticket_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHeadExt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHeadExt_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      fksproto.CsPdu.CSPDUPBHeadExt.class, fksproto.CsPdu.CSPDUPBHeadExt.Builder.class);
    }

    public static com.google.protobuf.Parser<CSPDUPBHeadExt> PARSER =
            new com.google.protobuf.AbstractParser<CSPDUPBHeadExt>() {
              public CSPDUPBHeadExt parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new CSPDUPBHeadExt(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<CSPDUPBHeadExt> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UIN_FIELD_NUMBER = 1;
    private int uin_;
    /**
     * <code>required int32 uin = 1;</code>
     */
    public boolean hasUin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 uin = 1;</code>
     */
    public int getUin() {
      return uin_;
    }

    public static final int TICKET_FIELD_NUMBER = 2;
    private java.lang.Object ticket_;
    /**
     * <code>required string ticket = 2;</code>
     */
    public boolean hasTicket() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string ticket = 2;</code>
     */
    public java.lang.String getTicket() {
      java.lang.Object ref = ticket_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ticket_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ticket = 2;</code>
     */
    public com.google.protobuf.ByteString
    getTicketBytes() {
      java.lang.Object ref = ticket_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        ticket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      uin_ = 0;
      ticket_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTicket()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTicketBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, uin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(2, getTicketBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fksproto.CsPdu.CSPDUPBHeadExt parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fksproto.CsPdu.CSPDUPBHeadExt parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fksproto.CsPdu.CSPDUPBHeadExt parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fksproto.CsPdu.CSPDUPBHeadExt parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fksproto.CsPdu.CSPDUPBHeadExt parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fksproto.CsPdu.CSPDUPBHeadExt parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fksproto.CsPdu.CSPDUPBHeadExt parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fksproto.CsPdu.CSPDUPBHeadExt parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fksproto.CsPdu.CSPDUPBHeadExt parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fksproto.CsPdu.CSPDUPBHeadExt parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fksproto.CsPdu.CSPDUPBHeadExt prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fksproto.CSPDUPBHeadExt}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:fksproto.CSPDUPBHeadExt)
            fksproto.CsPdu.CSPDUPBHeadExtOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHeadExt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHeadExt_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        fksproto.CsPdu.CSPDUPBHeadExt.class, fksproto.CsPdu.CSPDUPBHeadExt.Builder.class);
      }

      // Construct using fksproto.CsPdu.CSPDUPBHeadExt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ticket_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHeadExt_descriptor;
      }

      public fksproto.CsPdu.CSPDUPBHeadExt getDefaultInstanceForType() {
        return fksproto.CsPdu.CSPDUPBHeadExt.getDefaultInstance();
      }

      public fksproto.CsPdu.CSPDUPBHeadExt build() {
        fksproto.CsPdu.CSPDUPBHeadExt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fksproto.CsPdu.CSPDUPBHeadExt buildPartial() {
        fksproto.CsPdu.CSPDUPBHeadExt result = new fksproto.CsPdu.CSPDUPBHeadExt(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uin_ = uin_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ticket_ = ticket_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fksproto.CsPdu.CSPDUPBHeadExt) {
          return mergeFrom((fksproto.CsPdu.CSPDUPBHeadExt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fksproto.CsPdu.CSPDUPBHeadExt other) {
        if (other == fksproto.CsPdu.CSPDUPBHeadExt.getDefaultInstance()) return this;
        if (other.hasUin()) {
          setUin(other.getUin());
        }
        if (other.hasTicket()) {
          bitField0_ |= 0x00000002;
          ticket_ = other.ticket_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUin()) {

          return false;
        }
        if (!hasTicket()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        fksproto.CsPdu.CSPDUPBHeadExt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fksproto.CsPdu.CSPDUPBHeadExt) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int uin_ ;
      /**
       * <code>required int32 uin = 1;</code>
       */
      public boolean hasUin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 uin = 1;</code>
       */
      public int getUin() {
        return uin_;
      }
      /**
       * <code>required int32 uin = 1;</code>
       */
      public Builder setUin(int value) {
        bitField0_ |= 0x00000001;
        uin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 uin = 1;</code>
       */
      public Builder clearUin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uin_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ticket_ = "";
      /**
       * <code>required string ticket = 2;</code>
       */
      public boolean hasTicket() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string ticket = 2;</code>
       */
      public java.lang.String getTicket() {
        java.lang.Object ref = ticket_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ticket_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ticket = 2;</code>
       */
      public com.google.protobuf.ByteString
      getTicketBytes() {
        java.lang.Object ref = ticket_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          ticket_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ticket = 2;</code>
       */
      public Builder setTicket(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        ticket_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ticket = 2;</code>
       */
      public Builder clearTicket() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ticket_ = getDefaultInstance().getTicket();
        onChanged();
        return this;
      }
      /**
       * <code>required string ticket = 2;</code>
       */
      public Builder setTicketBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        ticket_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fksproto.CSPDUPBHeadExt)
    }

    static {
      defaultInstance = new CSPDUPBHeadExt(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:fksproto.CSPDUPBHeadExt)
  }

  public interface CSPDUPBHeadOrBuilder extends
          // @@protoc_insertion_point(interface_extends:fksproto.CSPDUPBHead)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
     */
    boolean hasBase();
    /**
     * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
     */
    fksproto.CsPdu.CSPDUPBHeadBase getBase();
    /**
     * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
     */
    fksproto.CsPdu.CSPDUPBHeadBaseOrBuilder getBaseOrBuilder();

    /**
     * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
     */
    boolean hasExt();
    /**
     * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
     */
    fksproto.CsPdu.CSPDUPBHeadExt getExt();
    /**
     * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
     */
    fksproto.CsPdu.CSPDUPBHeadExtOrBuilder getExtOrBuilder();
  }
  /**
   * Protobuf type {@code fksproto.CSPDUPBHead}
   */
  public static final class CSPDUPBHead extends
          com.google.protobuf.GeneratedMessage implements
          // @@protoc_insertion_point(message_implements:fksproto.CSPDUPBHead)
          CSPDUPBHeadOrBuilder {
    // Use CSPDUPBHead.newBuilder() to construct.
    private CSPDUPBHead(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CSPDUPBHead(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CSPDUPBHead defaultInstance;
    public static CSPDUPBHead getDefaultInstance() {
      return defaultInstance;
    }

    public CSPDUPBHead getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CSPDUPBHead(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              fksproto.CsPdu.CSPDUPBHeadBase.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = base_.toBuilder();
              }
              base_ = input.readMessage(fksproto.CsPdu.CSPDUPBHeadBase.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(base_);
                base_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              fksproto.CsPdu.CSPDUPBHeadExt.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = ext_.toBuilder();
              }
              ext_ = input.readMessage(fksproto.CsPdu.CSPDUPBHeadExt.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ext_);
                ext_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHead_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHead_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      fksproto.CsPdu.CSPDUPBHead.class, fksproto.CsPdu.CSPDUPBHead.Builder.class);
    }

    public static com.google.protobuf.Parser<CSPDUPBHead> PARSER =
            new com.google.protobuf.AbstractParser<CSPDUPBHead>() {
              public CSPDUPBHead parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new CSPDUPBHead(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<CSPDUPBHead> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BASE_FIELD_NUMBER = 1;
    private fksproto.CsPdu.CSPDUPBHeadBase base_;
    /**
     * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
     */
    public boolean hasBase() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
     */
    public fksproto.CsPdu.CSPDUPBHeadBase getBase() {
      return base_;
    }
    /**
     * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
     */
    public fksproto.CsPdu.CSPDUPBHeadBaseOrBuilder getBaseOrBuilder() {
      return base_;
    }

    public static final int EXT_FIELD_NUMBER = 2;
    private fksproto.CsPdu.CSPDUPBHeadExt ext_;
    /**
     * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
     */
    public boolean hasExt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
     */
    public fksproto.CsPdu.CSPDUPBHeadExt getExt() {
      return ext_;
    }
    /**
     * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
     */
    public fksproto.CsPdu.CSPDUPBHeadExtOrBuilder getExtOrBuilder() {
      return ext_;
    }

    private void initFields() {
      base_ = fksproto.CsPdu.CSPDUPBHeadBase.getDefaultInstance();
      ext_ = fksproto.CsPdu.CSPDUPBHeadExt.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBase()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getBase().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasExt()) {
        if (!getExt().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, base_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, ext_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, base_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(2, ext_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fksproto.CsPdu.CSPDUPBHead parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fksproto.CsPdu.CSPDUPBHead parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fksproto.CsPdu.CSPDUPBHead parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fksproto.CsPdu.CSPDUPBHead parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fksproto.CsPdu.CSPDUPBHead parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fksproto.CsPdu.CSPDUPBHead parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fksproto.CsPdu.CSPDUPBHead parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fksproto.CsPdu.CSPDUPBHead parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fksproto.CsPdu.CSPDUPBHead parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fksproto.CsPdu.CSPDUPBHead parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fksproto.CsPdu.CSPDUPBHead prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fksproto.CSPDUPBHead}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:fksproto.CSPDUPBHead)
            fksproto.CsPdu.CSPDUPBHeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHead_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHead_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        fksproto.CsPdu.CSPDUPBHead.class, fksproto.CsPdu.CSPDUPBHead.Builder.class);
      }

      // Construct using fksproto.CsPdu.CSPDUPBHead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBaseFieldBuilder();
          getExtFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (baseBuilder_ == null) {
          base_ = fksproto.CsPdu.CSPDUPBHeadBase.getDefaultInstance();
        } else {
          baseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (extBuilder_ == null) {
          ext_ = fksproto.CsPdu.CSPDUPBHeadExt.getDefaultInstance();
        } else {
          extBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return fksproto.CsPdu.internal_static_fksproto_CSPDUPBHead_descriptor;
      }

      public fksproto.CsPdu.CSPDUPBHead getDefaultInstanceForType() {
        return fksproto.CsPdu.CSPDUPBHead.getDefaultInstance();
      }

      public fksproto.CsPdu.CSPDUPBHead build() {
        fksproto.CsPdu.CSPDUPBHead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fksproto.CsPdu.CSPDUPBHead buildPartial() {
        fksproto.CsPdu.CSPDUPBHead result = new fksproto.CsPdu.CSPDUPBHead(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (baseBuilder_ == null) {
          result.base_ = base_;
        } else {
          result.base_ = baseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (extBuilder_ == null) {
          result.ext_ = ext_;
        } else {
          result.ext_ = extBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fksproto.CsPdu.CSPDUPBHead) {
          return mergeFrom((fksproto.CsPdu.CSPDUPBHead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fksproto.CsPdu.CSPDUPBHead other) {
        if (other == fksproto.CsPdu.CSPDUPBHead.getDefaultInstance()) return this;
        if (other.hasBase()) {
          mergeBase(other.getBase());
        }
        if (other.hasExt()) {
          mergeExt(other.getExt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBase()) {

          return false;
        }
        if (!getBase().isInitialized()) {

          return false;
        }
        if (hasExt()) {
          if (!getExt().isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        fksproto.CsPdu.CSPDUPBHead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fksproto.CsPdu.CSPDUPBHead) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private fksproto.CsPdu.CSPDUPBHeadBase base_ = fksproto.CsPdu.CSPDUPBHeadBase.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
              fksproto.CsPdu.CSPDUPBHeadBase, fksproto.CsPdu.CSPDUPBHeadBase.Builder, fksproto.CsPdu.CSPDUPBHeadBaseOrBuilder> baseBuilder_;
      /**
       * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
       */
      public boolean hasBase() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
       */
      public fksproto.CsPdu.CSPDUPBHeadBase getBase() {
        if (baseBuilder_ == null) {
          return base_;
        } else {
          return baseBuilder_.getMessage();
        }
      }
      /**
       * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
       */
      public Builder setBase(fksproto.CsPdu.CSPDUPBHeadBase value) {
        if (baseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          base_ = value;
          onChanged();
        } else {
          baseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
       */
      public Builder setBase(
              fksproto.CsPdu.CSPDUPBHeadBase.Builder builderForValue) {
        if (baseBuilder_ == null) {
          base_ = builderForValue.build();
          onChanged();
        } else {
          baseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
       */
      public Builder mergeBase(fksproto.CsPdu.CSPDUPBHeadBase value) {
        if (baseBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
                  base_ != fksproto.CsPdu.CSPDUPBHeadBase.getDefaultInstance()) {
            base_ =
                    fksproto.CsPdu.CSPDUPBHeadBase.newBuilder(base_).mergeFrom(value).buildPartial();
          } else {
            base_ = value;
          }
          onChanged();
        } else {
          baseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
       */
      public Builder clearBase() {
        if (baseBuilder_ == null) {
          base_ = fksproto.CsPdu.CSPDUPBHeadBase.getDefaultInstance();
          onChanged();
        } else {
          baseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
       */
      public fksproto.CsPdu.CSPDUPBHeadBase.Builder getBaseBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBaseFieldBuilder().getBuilder();
      }
      /**
       * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
       */
      public fksproto.CsPdu.CSPDUPBHeadBaseOrBuilder getBaseOrBuilder() {
        if (baseBuilder_ != null) {
          return baseBuilder_.getMessageOrBuilder();
        } else {
          return base_;
        }
      }
      /**
       * <code>required .fksproto.CSPDUPBHeadBase base = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
              fksproto.CsPdu.CSPDUPBHeadBase, fksproto.CsPdu.CSPDUPBHeadBase.Builder, fksproto.CsPdu.CSPDUPBHeadBaseOrBuilder>
      getBaseFieldBuilder() {
        if (baseBuilder_ == null) {
          baseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                  fksproto.CsPdu.CSPDUPBHeadBase, fksproto.CsPdu.CSPDUPBHeadBase.Builder, fksproto.CsPdu.CSPDUPBHeadBaseOrBuilder>(
                  getBase(),
                  getParentForChildren(),
                  isClean());
          base_ = null;
        }
        return baseBuilder_;
      }

      private fksproto.CsPdu.CSPDUPBHeadExt ext_ = fksproto.CsPdu.CSPDUPBHeadExt.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
              fksproto.CsPdu.CSPDUPBHeadExt, fksproto.CsPdu.CSPDUPBHeadExt.Builder, fksproto.CsPdu.CSPDUPBHeadExtOrBuilder> extBuilder_;
      /**
       * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
       */
      public boolean hasExt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
       */
      public fksproto.CsPdu.CSPDUPBHeadExt getExt() {
        if (extBuilder_ == null) {
          return ext_;
        } else {
          return extBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
       */
      public Builder setExt(fksproto.CsPdu.CSPDUPBHeadExt value) {
        if (extBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ext_ = value;
          onChanged();
        } else {
          extBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
       */
      public Builder setExt(
              fksproto.CsPdu.CSPDUPBHeadExt.Builder builderForValue) {
        if (extBuilder_ == null) {
          ext_ = builderForValue.build();
          onChanged();
        } else {
          extBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
       */
      public Builder mergeExt(fksproto.CsPdu.CSPDUPBHeadExt value) {
        if (extBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
                  ext_ != fksproto.CsPdu.CSPDUPBHeadExt.getDefaultInstance()) {
            ext_ =
                    fksproto.CsPdu.CSPDUPBHeadExt.newBuilder(ext_).mergeFrom(value).buildPartial();
          } else {
            ext_ = value;
          }
          onChanged();
        } else {
          extBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
       */
      public Builder clearExt() {
        if (extBuilder_ == null) {
          ext_ = fksproto.CsPdu.CSPDUPBHeadExt.getDefaultInstance();
          onChanged();
        } else {
          extBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
       */
      public fksproto.CsPdu.CSPDUPBHeadExt.Builder getExtBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getExtFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
       */
      public fksproto.CsPdu.CSPDUPBHeadExtOrBuilder getExtOrBuilder() {
        if (extBuilder_ != null) {
          return extBuilder_.getMessageOrBuilder();
        } else {
          return ext_;
        }
      }
      /**
       * <code>optional .fksproto.CSPDUPBHeadExt ext = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
              fksproto.CsPdu.CSPDUPBHeadExt, fksproto.CsPdu.CSPDUPBHeadExt.Builder, fksproto.CsPdu.CSPDUPBHeadExtOrBuilder>
      getExtFieldBuilder() {
        if (extBuilder_ == null) {
          extBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                  fksproto.CsPdu.CSPDUPBHeadExt, fksproto.CsPdu.CSPDUPBHeadExt.Builder, fksproto.CsPdu.CSPDUPBHeadExtOrBuilder>(
                  getExt(),
                  getParentForChildren(),
                  isClean());
          ext_ = null;
        }
        return extBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:fksproto.CSPDUPBHead)
    }

    static {
      defaultInstance = new CSPDUPBHead(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:fksproto.CSPDUPBHead)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_fksproto_CSPDUPBHeadBase_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_fksproto_CSPDUPBHeadBase_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_fksproto_CSPDUPBHeadExt_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_fksproto_CSPDUPBHeadExt_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_fksproto_CSPDUPBHead_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_fksproto_CSPDUPBHead_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\014cs_pdu.proto\022\010fksproto\"a\n\017CSPDUPBHeadB" +
                    "ase\022\r\n\005msgid\030\001 \002(\005\022\026\n\016encrypt_method\030\002 \002" +
                    "(\005\022\027\n\017compress_method\030\003 \002(\005\022\016\n\006result\030\004 " +
                    "\001(\005\"-\n\016CSPDUPBHeadExt\022\013\n\003uin\030\001 \002(\005\022\016\n\006ti" +
                    "cket\030\002 \002(\t\"]\n\013CSPDUPBHead\022\'\n\004base\030\001 \002(\0132" +
                    "\031.fksproto.CSPDUPBHeadBase\022%\n\003ext\030\002 \001(\0132" +
                    "\030.fksproto.CSPDUPBHeadExt*]\n\022CSPDUEncryp" +
                    "tMethod\022\027\n\023ENCRYPT_METHOD_NONE\020\000\022\026\n\022ENCR" +
                    "YPT_METHOD_AES\020\001\022\026\n\022ENCRYPT_METHOD_RSA\020\002" +
                    "*I\n\023CSPDUCompressMethod\022\030\n\024COMPRESS_METH",
            "OD_NONE\020\000\022\030\n\024COMPRESS_METHOD_GZIP\020\001*b\n\rC" +
                    "SPDUAuthType\022\022\n\016AUTH_TYPE_NONE\020\000\022\021\n\rAUTH" +
                    "_TYPE_SSO\020\001\022\024\n\020AUTH_TYPE_WXAUTH\020\002\022\024\n\020AUT" +
                    "H_TYPE_QQAUTH\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_fksproto_CSPDUPBHeadBase_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_fksproto_CSPDUPBHeadBase_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_fksproto_CSPDUPBHeadBase_descriptor,
            new java.lang.String[] { "Msgid", "EncryptMethod", "CompressMethod", "Result", });
    internal_static_fksproto_CSPDUPBHeadExt_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_fksproto_CSPDUPBHeadExt_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_fksproto_CSPDUPBHeadExt_descriptor,
            new java.lang.String[] { "Uin", "Ticket", });
    internal_static_fksproto_CSPDUPBHead_descriptor =
            getDescriptor().getMessageTypes().get(2);
    internal_static_fksproto_CSPDUPBHead_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_fksproto_CSPDUPBHead_descriptor,
            new java.lang.String[] { "Base", "Ext", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
