// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_info.proto

package fksproto;

public final class CsInfo {
  private CsInfo() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetVersionInfoRequestOrBuilder extends
          // @@protoc_insertion_point(interface_extends:fksproto.GetVersionInfoRequest)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .fksproto.BaseRequest head = 1;</code>
     */
    boolean hasHead();
    /**
     * <code>required .fksproto.BaseRequest head = 1;</code>
     */
    fksproto.CsHead.BaseRequest getHead();
    /**
     * <code>required .fksproto.BaseRequest head = 1;</code>
     */
    fksproto.CsHead.BaseRequestOrBuilder getHeadOrBuilder();

    /**
     * <code>optional int32 apptype = 2;</code>
     */
    boolean hasApptype();
    /**
     * <code>optional int32 apptype = 2;</code>
     */
    int getApptype();

    /**
     * <code>optional string localecode = 3;</code>
     *
     * <pre>
     *语种
     * </pre>
     */
    boolean hasLocalecode();
    /**
     * <code>optional string localecode = 3;</code>
     *
     * <pre>
     *语种
     * </pre>
     */
    java.lang.String getLocalecode();
    /**
     * <code>optional string localecode = 3;</code>
     *
     * <pre>
     *语种
     * </pre>
     */
    com.google.protobuf.ByteString
    getLocalecodeBytes();
  }
  /**
   * Protobuf type {@code fksproto.GetVersionInfoRequest}
   *
   * <pre>
   *add by jack.zuoquan
   * </pre>
   */
  public static final class GetVersionInfoRequest extends
          com.google.protobuf.GeneratedMessage implements
          // @@protoc_insertion_point(message_implements:fksproto.GetVersionInfoRequest)
          GetVersionInfoRequestOrBuilder {
    // Use GetVersionInfoRequest.newBuilder() to construct.
    private GetVersionInfoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetVersionInfoRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetVersionInfoRequest defaultInstance;
    public static GetVersionInfoRequest getDefaultInstance() {
      return defaultInstance;
    }

    public GetVersionInfoRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetVersionInfoRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              fksproto.CsHead.BaseRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = head_.toBuilder();
              }
              head_ = input.readMessage(fksproto.CsHead.BaseRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(head_);
                head_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              apptype_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              localecode_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return fksproto.CsInfo.internal_static_fksproto_GetVersionInfoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return fksproto.CsInfo.internal_static_fksproto_GetVersionInfoRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      fksproto.CsInfo.GetVersionInfoRequest.class, fksproto.CsInfo.GetVersionInfoRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<GetVersionInfoRequest> PARSER =
            new com.google.protobuf.AbstractParser<GetVersionInfoRequest>() {
              public GetVersionInfoRequest parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new GetVersionInfoRequest(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<GetVersionInfoRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HEAD_FIELD_NUMBER = 1;
    private fksproto.CsHead.BaseRequest head_;
    /**
     * <code>required .fksproto.BaseRequest head = 1;</code>
     */
    public boolean hasHead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .fksproto.BaseRequest head = 1;</code>
     */
    public fksproto.CsHead.BaseRequest getHead() {
      return head_;
    }
    /**
     * <code>required .fksproto.BaseRequest head = 1;</code>
     */
    public fksproto.CsHead.BaseRequestOrBuilder getHeadOrBuilder() {
      return head_;
    }

    public static final int APPTYPE_FIELD_NUMBER = 2;
    private int apptype_;
    /**
     * <code>optional int32 apptype = 2;</code>
     */
    public boolean hasApptype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 apptype = 2;</code>
     */
    public int getApptype() {
      return apptype_;
    }

    public static final int LOCALECODE_FIELD_NUMBER = 3;
    private java.lang.Object localecode_;
    /**
     * <code>optional string localecode = 3;</code>
     *
     * <pre>
     *语种
     * </pre>
     */
    public boolean hasLocalecode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string localecode = 3;</code>
     *
     * <pre>
     *语种
     * </pre>
     */
    public java.lang.String getLocalecode() {
      java.lang.Object ref = localecode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localecode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string localecode = 3;</code>
     *
     * <pre>
     *语种
     * </pre>
     */
    public com.google.protobuf.ByteString
    getLocalecodeBytes() {
      java.lang.Object ref = localecode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        localecode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      head_ = fksproto.CsHead.BaseRequest.getDefaultInstance();
      apptype_ = 0;
      localecode_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, apptype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLocalecodeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(2, apptype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(3, getLocalecodeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fksproto.CsInfo.GetVersionInfoRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fksproto.CsInfo.GetVersionInfoRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fksproto.CsInfo.GetVersionInfoRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fksproto.CsInfo.GetVersionInfoRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fksproto.CsInfo.GetVersionInfoRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fksproto.CsInfo.GetVersionInfoRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fksproto.CsInfo.GetVersionInfoRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fksproto.CsInfo.GetVersionInfoRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fksproto.CsInfo.GetVersionInfoRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fksproto.CsInfo.GetVersionInfoRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fksproto.CsInfo.GetVersionInfoRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fksproto.GetVersionInfoRequest}
     *
     * <pre>
     *add by jack.zuoquan
     * </pre>
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:fksproto.GetVersionInfoRequest)
            fksproto.CsInfo.GetVersionInfoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return fksproto.CsInfo.internal_static_fksproto_GetVersionInfoRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return fksproto.CsInfo.internal_static_fksproto_GetVersionInfoRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        fksproto.CsInfo.GetVersionInfoRequest.class, fksproto.CsInfo.GetVersionInfoRequest.Builder.class);
      }

      // Construct using fksproto.CsInfo.GetVersionInfoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeadFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headBuilder_ == null) {
          head_ = fksproto.CsHead.BaseRequest.getDefaultInstance();
        } else {
          headBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        apptype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        localecode_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return fksproto.CsInfo.internal_static_fksproto_GetVersionInfoRequest_descriptor;
      }

      public fksproto.CsInfo.GetVersionInfoRequest getDefaultInstanceForType() {
        return fksproto.CsInfo.GetVersionInfoRequest.getDefaultInstance();
      }

      public fksproto.CsInfo.GetVersionInfoRequest build() {
        fksproto.CsInfo.GetVersionInfoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fksproto.CsInfo.GetVersionInfoRequest buildPartial() {
        fksproto.CsInfo.GetVersionInfoRequest result = new fksproto.CsInfo.GetVersionInfoRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headBuilder_ == null) {
          result.head_ = head_;
        } else {
          result.head_ = headBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.apptype_ = apptype_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.localecode_ = localecode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fksproto.CsInfo.GetVersionInfoRequest) {
          return mergeFrom((fksproto.CsInfo.GetVersionInfoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fksproto.CsInfo.GetVersionInfoRequest other) {
        if (other == fksproto.CsInfo.GetVersionInfoRequest.getDefaultInstance()) return this;
        if (other.hasHead()) {
          mergeHead(other.getHead());
        }
        if (other.hasApptype()) {
          setApptype(other.getApptype());
        }
        if (other.hasLocalecode()) {
          bitField0_ |= 0x00000004;
          localecode_ = other.localecode_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHead()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        fksproto.CsInfo.GetVersionInfoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fksproto.CsInfo.GetVersionInfoRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private fksproto.CsHead.BaseRequest head_ = fksproto.CsHead.BaseRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
              fksproto.CsHead.BaseRequest, fksproto.CsHead.BaseRequest.Builder, fksproto.CsHead.BaseRequestOrBuilder> headBuilder_;
      /**
       * <code>required .fksproto.BaseRequest head = 1;</code>
       */
      public boolean hasHead() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .fksproto.BaseRequest head = 1;</code>
       */
      public fksproto.CsHead.BaseRequest getHead() {
        if (headBuilder_ == null) {
          return head_;
        } else {
          return headBuilder_.getMessage();
        }
      }
      /**
       * <code>required .fksproto.BaseRequest head = 1;</code>
       */
      public Builder setHead(fksproto.CsHead.BaseRequest value) {
        if (headBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          head_ = value;
          onChanged();
        } else {
          headBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .fksproto.BaseRequest head = 1;</code>
       */
      public Builder setHead(
              fksproto.CsHead.BaseRequest.Builder builderForValue) {
        if (headBuilder_ == null) {
          head_ = builderForValue.build();
          onChanged();
        } else {
          headBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .fksproto.BaseRequest head = 1;</code>
       */
      public Builder mergeHead(fksproto.CsHead.BaseRequest value) {
        if (headBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
                  head_ != fksproto.CsHead.BaseRequest.getDefaultInstance()) {
            head_ =
                    fksproto.CsHead.BaseRequest.newBuilder(head_).mergeFrom(value).buildPartial();
          } else {
            head_ = value;
          }
          onChanged();
        } else {
          headBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .fksproto.BaseRequest head = 1;</code>
       */
      public Builder clearHead() {
        if (headBuilder_ == null) {
          head_ = fksproto.CsHead.BaseRequest.getDefaultInstance();
          onChanged();
        } else {
          headBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .fksproto.BaseRequest head = 1;</code>
       */
      public fksproto.CsHead.BaseRequest.Builder getHeadBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeadFieldBuilder().getBuilder();
      }
      /**
       * <code>required .fksproto.BaseRequest head = 1;</code>
       */
      public fksproto.CsHead.BaseRequestOrBuilder getHeadOrBuilder() {
        if (headBuilder_ != null) {
          return headBuilder_.getMessageOrBuilder();
        } else {
          return head_;
        }
      }
      /**
       * <code>required .fksproto.BaseRequest head = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
              fksproto.CsHead.BaseRequest, fksproto.CsHead.BaseRequest.Builder, fksproto.CsHead.BaseRequestOrBuilder>
      getHeadFieldBuilder() {
        if (headBuilder_ == null) {
          headBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                  fksproto.CsHead.BaseRequest, fksproto.CsHead.BaseRequest.Builder, fksproto.CsHead.BaseRequestOrBuilder>(
                  getHead(),
                  getParentForChildren(),
                  isClean());
          head_ = null;
        }
        return headBuilder_;
      }

      private int apptype_ ;
      /**
       * <code>optional int32 apptype = 2;</code>
       */
      public boolean hasApptype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 apptype = 2;</code>
       */
      public int getApptype() {
        return apptype_;
      }
      /**
       * <code>optional int32 apptype = 2;</code>
       */
      public Builder setApptype(int value) {
        bitField0_ |= 0x00000002;
        apptype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 apptype = 2;</code>
       */
      public Builder clearApptype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        apptype_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object localecode_ = "";
      /**
       * <code>optional string localecode = 3;</code>
       *
       * <pre>
       *语种
       * </pre>
       */
      public boolean hasLocalecode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string localecode = 3;</code>
       *
       * <pre>
       *语种
       * </pre>
       */
      public java.lang.String getLocalecode() {
        java.lang.Object ref = localecode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            localecode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string localecode = 3;</code>
       *
       * <pre>
       *语种
       * </pre>
       */
      public com.google.protobuf.ByteString
      getLocalecodeBytes() {
        java.lang.Object ref = localecode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          localecode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string localecode = 3;</code>
       *
       * <pre>
       *语种
       * </pre>
       */
      public Builder setLocalecode(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        localecode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string localecode = 3;</code>
       *
       * <pre>
       *语种
       * </pre>
       */
      public Builder clearLocalecode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        localecode_ = getDefaultInstance().getLocalecode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string localecode = 3;</code>
       *
       * <pre>
       *语种
       * </pre>
       */
      public Builder setLocalecodeBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        localecode_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fksproto.GetVersionInfoRequest)
    }

    static {
      defaultInstance = new GetVersionInfoRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:fksproto.GetVersionInfoRequest)
  }

  public interface GetVersionInfoResponseOrBuilder extends
          // @@protoc_insertion_point(interface_extends:fksproto.GetVersionInfoResponse)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .fksproto.BaseResponse head = 1;</code>
     */
    boolean hasHead();
    /**
     * <code>required .fksproto.BaseResponse head = 1;</code>
     */
    fksproto.CsHead.BaseResponse getHead();
    /**
     * <code>required .fksproto.BaseResponse head = 1;</code>
     */
    fksproto.CsHead.BaseResponseOrBuilder getHeadOrBuilder();

    /**
     * <code>optional string version = 2;</code>
     *
     * <pre>
     *版本信息
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>optional string version = 2;</code>
     *
     * <pre>
     *版本信息
     * </pre>
     */
    java.lang.String getVersion();
    /**
     * <code>optional string version = 2;</code>
     *
     * <pre>
     *版本信息
     * </pre>
     */
    com.google.protobuf.ByteString
    getVersionBytes();

    /**
     * <code>optional string downloadurl = 3;</code>
     *
     * <pre>
     *下载url
     * </pre>
     */
    boolean hasDownloadurl();
    /**
     * <code>optional string downloadurl = 3;</code>
     *
     * <pre>
     *下载url
     * </pre>
     */
    java.lang.String getDownloadurl();
    /**
     * <code>optional string downloadurl = 3;</code>
     *
     * <pre>
     *下载url
     * </pre>
     */
    com.google.protobuf.ByteString
    getDownloadurlBytes();

    /**
     * <code>optional string description = 4;</code>
     *
     * <pre>
     * 信息描述
     * </pre>
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 4;</code>
     *
     * <pre>
     * 信息描述
     * </pre>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 4;</code>
     *
     * <pre>
     * 信息描述
     * </pre>
     */
    com.google.protobuf.ByteString
    getDescriptionBytes();
  }
  /**
   * Protobuf type {@code fksproto.GetVersionInfoResponse}
   */
  public static final class GetVersionInfoResponse extends
          com.google.protobuf.GeneratedMessage implements
          // @@protoc_insertion_point(message_implements:fksproto.GetVersionInfoResponse)
          GetVersionInfoResponseOrBuilder {
    // Use GetVersionInfoResponse.newBuilder() to construct.
    private GetVersionInfoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetVersionInfoResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetVersionInfoResponse defaultInstance;
    public static GetVersionInfoResponse getDefaultInstance() {
      return defaultInstance;
    }

    public GetVersionInfoResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetVersionInfoResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              fksproto.CsHead.BaseResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = head_.toBuilder();
              }
              head_ = input.readMessage(fksproto.CsHead.BaseResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(head_);
                head_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              version_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              downloadurl_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              description_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return fksproto.CsInfo.internal_static_fksproto_GetVersionInfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return fksproto.CsInfo.internal_static_fksproto_GetVersionInfoResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      fksproto.CsInfo.GetVersionInfoResponse.class, fksproto.CsInfo.GetVersionInfoResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<GetVersionInfoResponse> PARSER =
            new com.google.protobuf.AbstractParser<GetVersionInfoResponse>() {
              public GetVersionInfoResponse parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new GetVersionInfoResponse(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<GetVersionInfoResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HEAD_FIELD_NUMBER = 1;
    private fksproto.CsHead.BaseResponse head_;
    /**
     * <code>required .fksproto.BaseResponse head = 1;</code>
     */
    public boolean hasHead() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .fksproto.BaseResponse head = 1;</code>
     */
    public fksproto.CsHead.BaseResponse getHead() {
      return head_;
    }
    /**
     * <code>required .fksproto.BaseResponse head = 1;</code>
     */
    public fksproto.CsHead.BaseResponseOrBuilder getHeadOrBuilder() {
      return head_;
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private java.lang.Object version_;
    /**
     * <code>optional string version = 2;</code>
     *
     * <pre>
     *版本信息
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string version = 2;</code>
     *
     * <pre>
     *版本信息
     * </pre>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          version_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string version = 2;</code>
     *
     * <pre>
     *版本信息
     * </pre>
     */
    public com.google.protobuf.ByteString
    getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOWNLOADURL_FIELD_NUMBER = 3;
    private java.lang.Object downloadurl_;
    /**
     * <code>optional string downloadurl = 3;</code>
     *
     * <pre>
     *下载url
     * </pre>
     */
    public boolean hasDownloadurl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string downloadurl = 3;</code>
     *
     * <pre>
     *下载url
     * </pre>
     */
    public java.lang.String getDownloadurl() {
      java.lang.Object ref = downloadurl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          downloadurl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string downloadurl = 3;</code>
     *
     * <pre>
     *下载url
     * </pre>
     */
    public com.google.protobuf.ByteString
    getDownloadurlBytes() {
      java.lang.Object ref = downloadurl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        downloadurl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private java.lang.Object description_;
    /**
     * <code>optional string description = 4;</code>
     *
     * <pre>
     * 信息描述
     * </pre>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string description = 4;</code>
     *
     * <pre>
     * 信息描述
     * </pre>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 4;</code>
     *
     * <pre>
     * 信息描述
     * </pre>
     */
    public com.google.protobuf.ByteString
    getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      head_ = fksproto.CsHead.BaseResponse.getDefaultInstance();
      version_ = "";
      downloadurl_ = "";
      description_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHead()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHead().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getVersionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDownloadurlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDescriptionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, head_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(2, getVersionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(3, getDownloadurlBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(4, getDescriptionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fksproto.CsInfo.GetVersionInfoResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fksproto.CsInfo.GetVersionInfoResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fksproto.CsInfo.GetVersionInfoResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fksproto.CsInfo.GetVersionInfoResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fksproto.CsInfo.GetVersionInfoResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fksproto.CsInfo.GetVersionInfoResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fksproto.CsInfo.GetVersionInfoResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fksproto.CsInfo.GetVersionInfoResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fksproto.CsInfo.GetVersionInfoResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fksproto.CsInfo.GetVersionInfoResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fksproto.CsInfo.GetVersionInfoResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fksproto.GetVersionInfoResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:fksproto.GetVersionInfoResponse)
            fksproto.CsInfo.GetVersionInfoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return fksproto.CsInfo.internal_static_fksproto_GetVersionInfoResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return fksproto.CsInfo.internal_static_fksproto_GetVersionInfoResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        fksproto.CsInfo.GetVersionInfoResponse.class, fksproto.CsInfo.GetVersionInfoResponse.Builder.class);
      }

      // Construct using fksproto.CsInfo.GetVersionInfoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeadFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headBuilder_ == null) {
          head_ = fksproto.CsHead.BaseResponse.getDefaultInstance();
        } else {
          headBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        downloadurl_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return fksproto.CsInfo.internal_static_fksproto_GetVersionInfoResponse_descriptor;
      }

      public fksproto.CsInfo.GetVersionInfoResponse getDefaultInstanceForType() {
        return fksproto.CsInfo.GetVersionInfoResponse.getDefaultInstance();
      }

      public fksproto.CsInfo.GetVersionInfoResponse build() {
        fksproto.CsInfo.GetVersionInfoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fksproto.CsInfo.GetVersionInfoResponse buildPartial() {
        fksproto.CsInfo.GetVersionInfoResponse result = new fksproto.CsInfo.GetVersionInfoResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headBuilder_ == null) {
          result.head_ = head_;
        } else {
          result.head_ = headBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.downloadurl_ = downloadurl_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fksproto.CsInfo.GetVersionInfoResponse) {
          return mergeFrom((fksproto.CsInfo.GetVersionInfoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fksproto.CsInfo.GetVersionInfoResponse other) {
        if (other == fksproto.CsInfo.GetVersionInfoResponse.getDefaultInstance()) return this;
        if (other.hasHead()) {
          mergeHead(other.getHead());
        }
        if (other.hasVersion()) {
          bitField0_ |= 0x00000002;
          version_ = other.version_;
          onChanged();
        }
        if (other.hasDownloadurl()) {
          bitField0_ |= 0x00000004;
          downloadurl_ = other.downloadurl_;
          onChanged();
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000008;
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHead()) {

          return false;
        }
        if (!getHead().isInitialized()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        fksproto.CsInfo.GetVersionInfoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fksproto.CsInfo.GetVersionInfoResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private fksproto.CsHead.BaseResponse head_ = fksproto.CsHead.BaseResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
              fksproto.CsHead.BaseResponse, fksproto.CsHead.BaseResponse.Builder, fksproto.CsHead.BaseResponseOrBuilder> headBuilder_;
      /**
       * <code>required .fksproto.BaseResponse head = 1;</code>
       */
      public boolean hasHead() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .fksproto.BaseResponse head = 1;</code>
       */
      public fksproto.CsHead.BaseResponse getHead() {
        if (headBuilder_ == null) {
          return head_;
        } else {
          return headBuilder_.getMessage();
        }
      }
      /**
       * <code>required .fksproto.BaseResponse head = 1;</code>
       */
      public Builder setHead(fksproto.CsHead.BaseResponse value) {
        if (headBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          head_ = value;
          onChanged();
        } else {
          headBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .fksproto.BaseResponse head = 1;</code>
       */
      public Builder setHead(
              fksproto.CsHead.BaseResponse.Builder builderForValue) {
        if (headBuilder_ == null) {
          head_ = builderForValue.build();
          onChanged();
        } else {
          headBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .fksproto.BaseResponse head = 1;</code>
       */
      public Builder mergeHead(fksproto.CsHead.BaseResponse value) {
        if (headBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
                  head_ != fksproto.CsHead.BaseResponse.getDefaultInstance()) {
            head_ =
                    fksproto.CsHead.BaseResponse.newBuilder(head_).mergeFrom(value).buildPartial();
          } else {
            head_ = value;
          }
          onChanged();
        } else {
          headBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .fksproto.BaseResponse head = 1;</code>
       */
      public Builder clearHead() {
        if (headBuilder_ == null) {
          head_ = fksproto.CsHead.BaseResponse.getDefaultInstance();
          onChanged();
        } else {
          headBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .fksproto.BaseResponse head = 1;</code>
       */
      public fksproto.CsHead.BaseResponse.Builder getHeadBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeadFieldBuilder().getBuilder();
      }
      /**
       * <code>required .fksproto.BaseResponse head = 1;</code>
       */
      public fksproto.CsHead.BaseResponseOrBuilder getHeadOrBuilder() {
        if (headBuilder_ != null) {
          return headBuilder_.getMessageOrBuilder();
        } else {
          return head_;
        }
      }
      /**
       * <code>required .fksproto.BaseResponse head = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
              fksproto.CsHead.BaseResponse, fksproto.CsHead.BaseResponse.Builder, fksproto.CsHead.BaseResponseOrBuilder>
      getHeadFieldBuilder() {
        if (headBuilder_ == null) {
          headBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                  fksproto.CsHead.BaseResponse, fksproto.CsHead.BaseResponse.Builder, fksproto.CsHead.BaseResponseOrBuilder>(
                  getHead(),
                  getParentForChildren(),
                  isClean());
          head_ = null;
        }
        return headBuilder_;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>optional string version = 2;</code>
       *
       * <pre>
       *版本信息
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string version = 2;</code>
       *
       * <pre>
       *版本信息
       * </pre>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            version_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string version = 2;</code>
       *
       * <pre>
       *版本信息
       * </pre>
       */
      public com.google.protobuf.ByteString
      getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string version = 2;</code>
       *
       * <pre>
       *版本信息
       * </pre>
       */
      public Builder setVersion(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 2;</code>
       *
       * <pre>
       *版本信息
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string version = 2;</code>
       *
       * <pre>
       *版本信息
       * </pre>
       */
      public Builder setVersionBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        version_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object downloadurl_ = "";
      /**
       * <code>optional string downloadurl = 3;</code>
       *
       * <pre>
       *下载url
       * </pre>
       */
      public boolean hasDownloadurl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string downloadurl = 3;</code>
       *
       * <pre>
       *下载url
       * </pre>
       */
      public java.lang.String getDownloadurl() {
        java.lang.Object ref = downloadurl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            downloadurl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string downloadurl = 3;</code>
       *
       * <pre>
       *下载url
       * </pre>
       */
      public com.google.protobuf.ByteString
      getDownloadurlBytes() {
        java.lang.Object ref = downloadurl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          downloadurl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string downloadurl = 3;</code>
       *
       * <pre>
       *下载url
       * </pre>
       */
      public Builder setDownloadurl(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        downloadurl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string downloadurl = 3;</code>
       *
       * <pre>
       *下载url
       * </pre>
       */
      public Builder clearDownloadurl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        downloadurl_ = getDefaultInstance().getDownloadurl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string downloadurl = 3;</code>
       *
       * <pre>
       *下载url
       * </pre>
       */
      public Builder setDownloadurlBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        downloadurl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 4;</code>
       *
       * <pre>
       * 信息描述
       * </pre>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string description = 4;</code>
       *
       * <pre>
       * 信息描述
       * </pre>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 4;</code>
       *
       * <pre>
       * 信息描述
       * </pre>
       */
      public com.google.protobuf.ByteString
      getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 4;</code>
       *
       * <pre>
       * 信息描述
       * </pre>
       */
      public Builder setDescription(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 4;</code>
       *
       * <pre>
       * 信息描述
       * </pre>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000008);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 4;</code>
       *
       * <pre>
       * 信息描述
       * </pre>
       */
      public Builder setDescriptionBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        description_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fksproto.GetVersionInfoResponse)
    }

    static {
      defaultInstance = new GetVersionInfoResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:fksproto.GetVersionInfoResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_fksproto_GetVersionInfoRequest_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_fksproto_GetVersionInfoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_fksproto_GetVersionInfoResponse_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_fksproto_GetVersionInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\rcs_info.proto\022\010fksproto\032\rcs_head.proto" +
                    "\032\rcs_base.proto\"a\n\025GetVersionInfoRequest" +
                    "\022#\n\004head\030\001 \002(\0132\025.fksproto.BaseRequest\022\017\n" +
                    "\007apptype\030\002 \001(\005\022\022\n\nlocalecode\030\003 \001(\t\"y\n\026Ge" +
                    "tVersionInfoResponse\022$\n\004head\030\001 \002(\0132\026.fks" +
                    "proto.BaseResponse\022\017\n\007version\030\002 \001(\t\022\023\n\013d" +
                    "ownloadurl\030\003 \001(\t\022\023\n\013description\030\004 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                            fksproto.CsHead.getDescriptor(),
                            fksproto.CsBase.getDescriptor(),
                    }, assigner);
    internal_static_fksproto_GetVersionInfoRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_fksproto_GetVersionInfoRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_fksproto_GetVersionInfoRequest_descriptor,
            new java.lang.String[] { "Head", "Apptype", "Localecode", });
    internal_static_fksproto_GetVersionInfoResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_fksproto_GetVersionInfoResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_fksproto_GetVersionInfoResponse_descriptor,
            new java.lang.String[] { "Head", "Version", "Downloadurl", "Description", });
    fksproto.CsHead.getDescriptor();
    fksproto.CsBase.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}